/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EmployeeID = IDL.Text;
export const Designation = IDL.Variant({
  'accountant' : IDL.Null,
  'hvacTechnician' : IDL.Null,
  'logistics' : IDL.Null,
  'plumber' : IDL.Null,
  'laborer' : IDL.Null,
  'plumberHelper' : IDL.Null,
  'estimatorInTendering' : IDL.Null,
  'procurementProcurementSpecialist' : IDL.Null,
  'fabricator' : IDL.Null,
  'electricianSupervisor' : IDL.Null,
  'other' : IDL.Null,
  'civilForeman' : IDL.Null,
  'kitchenHelper' : IDL.Null,
  'cook' : IDL.Null,
  'siteTimekeeper' : IDL.Null,
  'cashier' : IDL.Null,
  'seniorEngineerTendering' : IDL.Null,
  'projectManagerKuwait' : IDL.Null,
  'generalClerk' : IDL.Null,
  'generalSupervisor' : IDL.Null,
  'painterSupervisor' : IDL.Null,
  'electrician' : IDL.Null,
  'mechanicalSupervisor' : IDL.Null,
  'mechanic' : IDL.Null,
  'cleanerSupervisor' : IDL.Null,
  'projectTechnical_manager' : IDL.Null,
  'storekeeper' : IDL.Null,
  'electricalForeman' : IDL.Null,
  'pmoOperations_director' : IDL.Null,
  'generalHelper' : IDL.Null,
  'maleNurse' : IDL.Null,
  'siteExpeditor' : IDL.Null,
  'mechanicalForeman' : IDL.Null,
  'attendant' : IDL.Null,
  'cleaner' : IDL.Null,
  'hrLabourDiscipline' : IDL.Null,
  'waiter' : IDL.Null,
  'lawnkeeper' : IDL.Null,
  'forkliftOperator' : IDL.Null,
  'painter' : IDL.Null,
  'matron' : IDL.Null,
  'adminGeneral' : IDL.Null,
  'pmoGeneral_manager' : IDL.Null,
  'projectManagerSuperIntendent' : IDL.Null,
  'civilSupervisor' : IDL.Null,
  'siteTimekeeperClerk' : IDL.Null,
  'therapist' : IDL.Null,
});
export const Location = IDL.Variant({
  'kuwait' : IDL.Null,
  'saudi' : IDL.Null,
});
export const EmployeeType = IDL.Variant({
  'supplier' : IDL.Null,
  'company' : IDL.Null,
});
export const Project = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Employee = IDL.Record({
  'id' : EmployeeID,
  'employeeType' : EmployeeType,
  'name' : IDL.Text,
  'designation' : Designation,
  'photo' : ExternalBlob,
  'location' : Location,
  'project' : IDL.Opt(Project),
});
export const WorkingStatus = IDL.Variant({
  'partialWork' : IDL.Null,
  'fullworkOvertime' : IDL.Null,
  'fullwork' : IDL.Null,
  'absent' : IDL.Null,
  'holiday' : IDL.Null,
  'vacation' : IDL.Null,
});
export const Time = IDL.Int;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func(
      [
        EmployeeID,
        IDL.Text,
        Designation,
        Location,
        EmployeeType,
        IDL.Opt(Project),
        ExternalBlob,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([EmployeeID], [Employee], ['query']),
  'getEmployeeWorkingStatus' : IDL.Func(
      [EmployeeID],
      [WorkingStatus],
      ['query'],
    ),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getOvertimeThreshold' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordCheckIn' : IDL.Func([EmployeeID, Time, WorkingStatus], [], []),
  'recordCheckOut' : IDL.Func([EmployeeID, Time], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setEmployeeWorkingStatus' : IDL.Func([EmployeeID, WorkingStatus], [], []),
  'setOvertimeThreshold' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EmployeeID = IDL.Text;
  const Designation = IDL.Variant({
    'accountant' : IDL.Null,
    'hvacTechnician' : IDL.Null,
    'logistics' : IDL.Null,
    'plumber' : IDL.Null,
    'laborer' : IDL.Null,
    'plumberHelper' : IDL.Null,
    'estimatorInTendering' : IDL.Null,
    'procurementProcurementSpecialist' : IDL.Null,
    'fabricator' : IDL.Null,
    'electricianSupervisor' : IDL.Null,
    'other' : IDL.Null,
    'civilForeman' : IDL.Null,
    'kitchenHelper' : IDL.Null,
    'cook' : IDL.Null,
    'siteTimekeeper' : IDL.Null,
    'cashier' : IDL.Null,
    'seniorEngineerTendering' : IDL.Null,
    'projectManagerKuwait' : IDL.Null,
    'generalClerk' : IDL.Null,
    'generalSupervisor' : IDL.Null,
    'painterSupervisor' : IDL.Null,
    'electrician' : IDL.Null,
    'mechanicalSupervisor' : IDL.Null,
    'mechanic' : IDL.Null,
    'cleanerSupervisor' : IDL.Null,
    'projectTechnical_manager' : IDL.Null,
    'storekeeper' : IDL.Null,
    'electricalForeman' : IDL.Null,
    'pmoOperations_director' : IDL.Null,
    'generalHelper' : IDL.Null,
    'maleNurse' : IDL.Null,
    'siteExpeditor' : IDL.Null,
    'mechanicalForeman' : IDL.Null,
    'attendant' : IDL.Null,
    'cleaner' : IDL.Null,
    'hrLabourDiscipline' : IDL.Null,
    'waiter' : IDL.Null,
    'lawnkeeper' : IDL.Null,
    'forkliftOperator' : IDL.Null,
    'painter' : IDL.Null,
    'matron' : IDL.Null,
    'adminGeneral' : IDL.Null,
    'pmoGeneral_manager' : IDL.Null,
    'projectManagerSuperIntendent' : IDL.Null,
    'civilSupervisor' : IDL.Null,
    'siteTimekeeperClerk' : IDL.Null,
    'therapist' : IDL.Null,
  });
  const Location = IDL.Variant({ 'kuwait' : IDL.Null, 'saudi' : IDL.Null });
  const EmployeeType = IDL.Variant({
    'supplier' : IDL.Null,
    'company' : IDL.Null,
  });
  const Project = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Employee = IDL.Record({
    'id' : EmployeeID,
    'employeeType' : EmployeeType,
    'name' : IDL.Text,
    'designation' : Designation,
    'photo' : ExternalBlob,
    'location' : Location,
    'project' : IDL.Opt(Project),
  });
  const WorkingStatus = IDL.Variant({
    'partialWork' : IDL.Null,
    'fullworkOvertime' : IDL.Null,
    'fullwork' : IDL.Null,
    'absent' : IDL.Null,
    'holiday' : IDL.Null,
    'vacation' : IDL.Null,
  });
  const Time = IDL.Int;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func(
        [
          EmployeeID,
          IDL.Text,
          Designation,
          Location,
          EmployeeType,
          IDL.Opt(Project),
          ExternalBlob,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([EmployeeID], [Employee], ['query']),
    'getEmployeeWorkingStatus' : IDL.Func(
        [EmployeeID],
        [WorkingStatus],
        ['query'],
      ),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getOvertimeThreshold' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordCheckIn' : IDL.Func([EmployeeID, Time, WorkingStatus], [], []),
    'recordCheckOut' : IDL.Func([EmployeeID, Time], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setEmployeeWorkingStatus' : IDL.Func([EmployeeID, WorkingStatus], [], []),
    'setOvertimeThreshold' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };