/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Designation = { 'accountant' : null } |
  { 'hvacTechnician' : null } |
  { 'logistics' : null } |
  { 'plumber' : null } |
  { 'laborer' : null } |
  { 'plumberHelper' : null } |
  { 'estimatorInTendering' : null } |
  { 'procurementProcurementSpecialist' : null } |
  { 'fabricator' : null } |
  { 'electricianSupervisor' : null } |
  { 'other' : null } |
  { 'civilForeman' : null } |
  { 'kitchenHelper' : null } |
  { 'cook' : null } |
  { 'siteTimekeeper' : null } |
  { 'cashier' : null } |
  { 'seniorEngineerTendering' : null } |
  { 'projectManagerKuwait' : null } |
  { 'generalClerk' : null } |
  { 'generalSupervisor' : null } |
  { 'painterSupervisor' : null } |
  { 'electrician' : null } |
  { 'mechanicalSupervisor' : null } |
  { 'mechanic' : null } |
  { 'cleanerSupervisor' : null } |
  { 'projectTechnical_manager' : null } |
  { 'storekeeper' : null } |
  { 'electricalForeman' : null } |
  { 'pmoOperations_director' : null } |
  { 'generalHelper' : null } |
  { 'maleNurse' : null } |
  { 'siteExpeditor' : null } |
  { 'mechanicalForeman' : null } |
  { 'attendant' : null } |
  { 'cleaner' : null } |
  { 'hrLabourDiscipline' : null } |
  { 'waiter' : null } |
  { 'lawnkeeper' : null } |
  { 'forkliftOperator' : null } |
  { 'painter' : null } |
  { 'matron' : null } |
  { 'adminGeneral' : null } |
  { 'pmoGeneral_manager' : null } |
  { 'projectManagerSuperIntendent' : null } |
  { 'civilSupervisor' : null } |
  { 'siteTimekeeperClerk' : null } |
  { 'therapist' : null };
export interface Employee {
  'id' : EmployeeID,
  'employeeType' : EmployeeType,
  'name' : string,
  'designation' : Designation,
  'photo' : ExternalBlob,
  'location' : Location,
  'project' : [] | [Project],
}
export type EmployeeID = string;
export type EmployeeType = { 'supplier' : null } |
  { 'company' : null };
export type ExternalBlob = Uint8Array;
export type Location = { 'kuwait' : null } |
  { 'saudi' : null };
export interface Project { 'name' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WorkingStatus = { 'partialWork' : null } |
  { 'fullworkOvertime' : null } |
  { 'fullwork' : null } |
  { 'absent' : null } |
  { 'holiday' : null } |
  { 'vacation' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployee' : ActorMethod<
    [
      EmployeeID,
      string,
      Designation,
      Location,
      EmployeeType,
      [] | [Project],
      ExternalBlob,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[EmployeeID], Employee>,
  'getEmployeeWorkingStatus' : ActorMethod<[EmployeeID], WorkingStatus>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'getOvertimeThreshold' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordCheckIn' : ActorMethod<[EmployeeID, Time, WorkingStatus], undefined>,
  'recordCheckOut' : ActorMethod<[EmployeeID, Time], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setEmployeeWorkingStatus' : ActorMethod<
    [EmployeeID, WorkingStatus],
    undefined
  >,
  'setOvertimeThreshold' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];